language: rust
rust:
- stable
- beta
- nightly
cache:
  cargo: true
matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly
  include:
  - stage: publish
    if: (type = push) && (tag =~ /^\d+\.\d+\.\d+/)
    script:
    - (cd ufix && cargo publish || true)
before_script:
- if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then rustup component add clippy rustfmt; fi
script:
- if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then cargo clippy --all -- -D warnings; fi
- if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then cargo fmt --all -- --check; fi
- cargo doc --all
- cargo test --all
- (cd uctl; cargo test --features i128)
- (cd ufix; cargo test --features word8)
- (cd ufix; cargo test --features word16)
- (cd ufix; cargo test --features word8,i128)
- (cd ufix; cargo test --features word16,i128)
- (cd uctl; cargo test --features i128)
